### PR TITLE
47 - HelpRequests - added table

### PR DESCRIPTION
**Pull request by alecsong222**

### CODE REVIEW

**Comment by alecsong222** [comment]
https://6726f348083baab74d18dd7c-acngkpnxpx.chromatic.com/?path=/docs/components-helprequest-helprequesttable--docs

**Comment by alecsong222** [comment]
image

**Comment by elijahelephant** [comment]
Looks good to me, mege when ready!

**Comment by neil-roy** [comment]
- everything looks good, all tests pass. Merging with main

**Pull request merged**
