### PR TITLE
59 added index and updated index tests for articles

### PR DESCRIPTION
**Pull request by SexyJesusFreak**
Screenshot 2024-11-08 at 10 33 06 PM

https://6726f348083baab74d18dd7c-gfetshmkey.chromatic.com/?path=/docs/pages-articles-articlesindexpage--docs

### CODE REVIEW

**Comment by SexyJesusFreak** [comment]
same issue with no checks

**Comment by SexyJesusFreak** [comment]
resolved checks now showing up

**Comment by alecsong222** [comment]
LGTM! Merged

**Comment by alecsong222** [comment]
LGTM! Merged

**Pull request merged**
